# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e56013db00885524cea40d924789305b4c0db9254e9ee980e2539df80dd5b4bb874a46a9b201b1a0ceb52a8d25a87aed13acc51bfdaec080d3fd511af1e6b62

test:
  secret_key_base: be42ebf9f53fc3daa49ec42df3902f83836cbb42da3ee62f7f5a1cd02f1387fd848a7632c77f90bbcabb3e9453cae5cc8cf9064ae931071a2baf99e1c578ec88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
